// Mocks generated by Mockito 5.0.14 from annotations
// in lafhub/test/login_repo_tests.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:lafhub/datasources/oauth2_client.dart' as _i2;
import 'package:lafhub/lafhub_entities.dart' as _i6;
import 'package:lafhub/lafhub_utils.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeOAuth2ClientConfigs_0 extends _i1.Fake
    implements _i2.OAuth2ClientConfigs {}

class _FakeEither_1<L, R> extends _i1.Fake implements _i3.Either<L, R> {}

/// A class which mocks [OAuth2ClientExpected].
///
/// See the documentation for Mockito's code generation for more information.
class MockOAuth2ClientExpected extends _i1.Mock
    implements _i2.OAuth2ClientExpected {
  MockOAuth2ClientExpected() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.OAuth2ClientConfigs getClientConfigs() => (super.noSuchMethod(
      Invocation.method(#getClientConfigs, []),
      returnValue: _FakeOAuth2ClientConfigs_0()) as _i2.OAuth2ClientConfigs);
  @override
  _i5.Future<_i3.Either<String, _i3.Failure>> processCallback(
          String? callback) =>
      (super.noSuchMethod(Invocation.method(#processCallback, [callback]),
              returnValue: Future<_i3.Either<String, _i3.Failure>>.value(
                  _FakeEither_1<String, _i3.Failure>()))
          as _i5.Future<_i3.Either<String, _i3.Failure>>);
  @override
  _i5.Future<_i3.Either<_i6.GHUserProfile, _i3.Failure>> getUserProfile() =>
      (super.noSuchMethod(Invocation.method(#getUserProfile, []),
          returnValue: Future<_i3.Either<_i6.GHUserProfile, _i3.Failure>>.value(
              _FakeEither_1<_i6.GHUserProfile, _i3.Failure>())) as _i5
          .Future<_i3.Either<_i6.GHUserProfile, _i3.Failure>>);
  @override
  void setAccessToken(String? token) =>
      super.noSuchMethod(Invocation.method(#setAccessToken, [token]),
          returnValueForMissingStub: null);
  @override
  void logoutUser() => super.noSuchMethod(Invocation.method(#logOutUser, []),
      returnValueForMissingStub: null);
  @override
  String toString() => super.toString();
}
